name: Semantic release

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      - name: Install dependencies
        run: yarn
      - name: Build app
        run: yarn build
      - name: Semantic release
        run: npx semantic-release
